backend:
  name: git-gateway
  branch: main

publish_mode: simple

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: https://duygital-portfolio.netlify.app
display_url: https://duygital-portfolio.netlify.app

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "General Info"
        name: "general"
        fields:
          - { label: "Site title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Published", name: "published", widget: "boolean", default: true }
